project:
  type: website
  output-dir: docs

website:
  title: "Christian Cobos"
  navbar:
    right:
      - about.qmd
      - personal.qmd


format:
  html:
    theme: lumen
    css: styles.css
    toc: true



