---
title: "Personal Statement"
format: html
editor: visual
---

## Personal Statement

Growing up in a predominantly Hispanic community, I have seen firsthand the disparities that exist in our society, educational system, and workforce. Hispanic graduates are underrepresented among STEM degree recipients and in STEM jobs in the U.S. Understanding the challenges a student like me faces has led to my strong commitment and desire to pursue a career in Mathematics. I am a first-generation Mexican American Chicano student with a passion for mathematics and statistics. I want to promote the importance of higher education. I want to serve as a role model to my family, my son, siblings, and greater Hispanic community as someone who pursued their dreams against all odds.

My interest in statistics and probability began in the summer of 2020 when I was first introduced to statistical analysis in the company I worked for as a Supplier Quality Associate. I conducted simple linear regression on small data sets of dimensional measurements of our inventory. It was when I discovered that I had a passion for Statistics. I abandoned my original goal of obtaining a Bachelor\'s Degree in Mechanical Engineering and pursued a degree in Mathematics in the area of Statistics. I am particularly interested in exploring topics related to data mining, directional data analysis, resampling techniques, linear models and generalized linear models, mixed effects models, systemic risk in the financial market, Stochastic volatility modeling, environmental statistics, and survival analysis. With the guidance of experienced mentors I am confident that I can make meaningful contributions to this field.

Throughout my personal life and academic journey, I have faced challenges that demonstrated the importance of perseverance and resilience. As a first-generation student, I navigated unfamiliar academic and social environments, and I learned to adapt and thrive in these situations. For example, I had difficulty adapting to college-level classes during my first semester at CSUCI. My performance in the first semester could have been better. This experience allowed me to look for the potential I never thought I had. I demonstrated the capabilities to excel in my field the following semester by being awarded Semester Honors and achieving my best performance in my entire academic journey. I have had many setbacks throughout my academic career. I did not have the opportunity to attend college after high school due to financial difficulties and the lack of access to information on financial aid during my high school years. I attended Oxnard Community College six months after my graduation but had to drop out after three months due to financial difficulties. Years later, I realized I needed a degree to give my son a better future. I worked and went to school for four years before transferring to CSUCI. I save money to be financially ready. After all those years of hard work, I am proud to say that I am in college pursuing my dream.

I am a driven and passionate student eager to participate in a program or company to enhance my educational and professional development. My commitment to my career is unwavering. I look forward to the days I can apply my skills and working knowledge to positively impact society. Contribute to diversity and representation of Hispanics in the STEM workforce. Last but not least, become a role model to my community and inspire students to pursue a career in STEM against all odds.
